DZ 2911h
fd1-53-17/Dzmitry-ZH pull request #21
Opened 2017-11-28 22:41 UTC by Dzmitry-ZH

@antonkulakov-it please rewiev

2017-11-29 05:11 UTC, antonkulakov-it requested changes

2017-11-29 05:11 UTC, antonkulakov-it commented on 2911h/1/assets/css/style.css
> +        height: 250px;
а если контент увеличится?

2017-11-30 15:43 UTC, Dzmitry-ZH commented
@antonkulakov-it Height correction DZ 2911h

2017-12-12 18:55 UTC, antonkulakov-it approved these changes

2017-12-12 18:55 UTC, merged