1011h
fd1-53-17/Dzmitry-ZH pull request #6
Opened 2017-11-08 20:25 UTC by Dzmitry-ZH

@antonkulakov-it please review DZ 10_11

2017-11-09 12:59 UTC, antonkulakov-it requested changes
Отправляйте только те файлы, которые нужны для выполнения задания.

2017-11-09 12:59 UTC, antonkulakov-it commented on .gitignore
> +# IntellijIdea files
это зачем мне?

2017-11-09 20:46 UTC, Dzmitry-ZH commented on .gitignore
> +# IntellijIdea files
Вам и не надо, мне надо. Я этот файлик у себя в локальном репозитории создал и закоммитил. Push автоматически все отправляет на github. Можно как-то убрать ненужные файлы из pull request?

2017-11-10 07:33 UTC, Dzmitry-ZH commented
@antonkulakov-it delete file .gitignore

2017-11-12 10:00 UTC, antonkulakov-it approved these changes

2017-11-12 10:00 UTC, merged